# Generated by Django 2.2.3 on 2020-05-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='categories',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
