# Generated by Django 2.2.3 on 2020-05-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendations', '0002_auto_20200503_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='bussines_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
