# Generated by Django 2.2.3 on 2020-05-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendations', '0005_recommendation_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user_name',
        ),
    ]
