# Generated by Django 2.2.3 on 2020-05-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendations', '0006_remove_recommendation_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='categories',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='review_count',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
    ]
