# Generated by Django 2.2.3 on 2020-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('bussiness_id', models.CharField(max_length=50)),
                ('bussiness_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
