# Generated by Django 2.2.3 on 2020-05-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='bussiness_id',
        ),
    ]
