# Generated by Django 2.2.3 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviews_bussiness_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
